### PR TITLE
Fix #8 Parse negative numbers

### LINKED ISSUE #8: Negative numbers don't work
When I type:
`var minx = 5`
it compiles successfully, but when I type:
`var minx = -5`
this happens:
`Error: Unexpected token: {"type":"num","value":5} (9:13) in file .//claims/data/claims/scripts/load.mcscript`
`    at Object.croak (C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\lexer.js:85:12)`
`    at unexpected (C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:58:11)`
`    at C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:629:7`
`    at maybe_call (C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:570:12)`
`    at parse_atom (C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:577:12)`
`    at maybe_binary (C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:92:35)`
`    at parse_var (C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:419:18)`
`    at C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:588:49`
`    at maybe_call (C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:570:12)`
`    at parse_atom (C:\Users\User\AppData\Roaming\npm\node_modules\mcscript\lib\parser.js:577:12)`

Edit: There is a workaround:
`var minx = 0`
`minx -= 5`

### PR DESCRIPTION
**Pull request by viniciuslrangel**
Fix #8

### CODE REVIEW

**Comment by Heath123** [comment]
There's no need to make a duplicate issue...

**Comment by Heath123** [comment]
Oh

**Comment by Heath123** [comment]
This is a PR

**Comment by Heath123** [comment]
Never mind

**Comment by Stevertus** [comment]
Sorry that this took so long, I was not aware that someone actually fixed this issue
Thank you soo much!

**Pull request merged**
